### ISSUE TITLE
Error: soap:Server: [PublisherQueryLanguageSyntaxError.UNPARSABLE @ Unable to parse query: 'Where '

### ISSUE THREAD

**Issue by brianibok** [spanishdict/node-google-dfp-wrapper#24]
Hi All,

Getting the error below when I try to run the script to generate the line-items:

node scripts/create-line-items.js --order ORDER_NAME --start 1 --end 1

Error:
Progress [=-] 50% 0.0screating line items failed
because Error: soap:Server: [PublisherQueryLanguageSyntaxError.UNPARSABLE @ Unable to parse query: 'Where '
Syntax error at line 0, column 0.]

However no modifications were made to the script

**Comment by JuanCaicedo** [comment]
I opened up this issue in https://github.com/spanishdict/example-dfp-line-item-generator
